import { getDatabase, ref, push, set } from "firebase/database";

// @ts-ignore
export async function logTime(time) {
  const db = getDatabase();
  const dbRef = ref(db, "UserData/CompletionTimes");

  const timestamp = new Date().toLocaleString();

  // Use push to generate a unique key based on timestamp
  const newCompletionRef = push(dbRef);

  set(newCompletionRef, {
    time: time,
    timestamp: timestamp,
  });

  // Retrieve the unique key generated by push
  const completionKey = newCompletionRef.key;

  return completionKey;
}